# Site
repository: nazarbabii/nazarbabii.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nazar Babii
title: Senior Software Development Engineer in Test


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: nbabii
linkedin_username: nbabii

# About Section
about_profile_image: images/profile.jpg
about_content: |
  - Senior Software Development Engineer in Test, with over 10 years of experience building QA automation frameworks.
   
  - Driven QA automation projects from scratch for SaaS, finance, healthcare, and e-commerce projects.
   
  - Proven background in building QA automated testing architecture and processes.
   
  - Mentored more than 15 engineers, providing professional guidance and facilitating their growth.

content:
  - title: Skills
    layout: text
    content: |
      **Languages**: JavaScript, Python, Java, SQL  
      **Frameworks**: WebdriverIO, Playwright, Appium, Selenium, Robot Framework, Gatling.io, Jmeter, Mocha, TestNG, Pytest, Jasmine.  
      **Cloud & Infra**: GCP, Azure.  
      **Tools**: BrowserStack, Perfecto, Sauce Labs, Node.js, CI/CD, SonarQube, Android SDK, iOS SDK (Xcode), Terraform, Twilio, Resemble.js, Octa, Mailtrap.io, Postman, Artillery.io, Gatling.io.  
      **Other Skills**: Agile, Scrum, Kanban, team leading, cross-teams collaborations, leadership communication.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Bitly Inc.
        sub_title: Senior Software Development Engineer in Test
        caption: Oct 2023 – Present
        quote: >
          SDET at SaaS platform for URL management and analytics.
        description: |
          - Implemented automated QA for SaaS web platform, data analytics, and internal data platform.
          - Participated in the technical POC for migrating the WebdriverIO framework to Playwright.
          - Designed data QA framework based on Google Cloud Platform.
          - Reduced data anomaly detection time from 72h to 24h.
          - Built internal QA analytics dashboards.

      - layout: right
        title: Eleks Inc.
        sub_title: Senior Software Development Engineer in Test
        caption: Sep 2022 – Oct 2023
        quote: >
          SDET at software consulting company, project: US healthcare corporation.
        description: |
          - Led automation strategy ensuring HIPAA compliance.
          - Boosted test coverage from 30% to 64%.
          - Cut flaky test rate from 21% to 6%.
          - Evaluated Perfecto and BrowserStack for test infra.

      - layout: right
        title: ELEKS Ltd.
        sub_title: Senior Software Development Engineer in Test
        caption: Aug 2017 – Sep 2022
        quote: >
          SDET at software consulting company, projects: US financial group, UK health and wellness group.
        description: |
          - Started and scaled JavaScript QA automation services.
          - Built frameworks for online banking and e-commerce.
          - Mentored 10+ SDETs and delivered multiple pre-sales POCs.
          - Led migration from Protractor to WebdriverIO.

      - layout: right
        title: N-iX
        sub_title: Senior Software Development Engineer in Test
        caption: Feb 2017 – Aug 2017
        quote: >
          SDET at software consulting company, project: US healthcare startup.
        description: |
          - Migrated automation from Java to Robot Framework + Python.
          - Implemented CI-integrated QA for patient health data app.

      - layout: right
        title: GlobalLogic
        sub_title: Software Development Engineer in Test
        caption: Feb 2015 – Feb 2017
        quote: >
          SDET at software consulting company, project: Lebanon financial group.
        description: |
          - E2E QA automation for finance and telecom apps.
          - Led and mentored team of 9; achieved ~70% test coverage.

      - layout: right
        title: ELEKS Ltd.
        sub_title: Software Engineer in Localization
        caption: Jan 2011 – Feb 2015
        quote: >
          Software Engineer at software consulting company, client: World-famous web security company.
        description: |
          - QA for desktop & web antivirus software.
          - Fixed 25%+ of automation-detected defects.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Master's in Computer Engineering & System Programming
        sub_title: Lviv Polytechnic National University
        caption: 2010

      - layout: top-right
        title: Bachelor's in Computer Engineering
        sub_title: Lviv Polytechnic National University
        caption: 2008

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
